spring.application.name=eventify

# Toggle del seeder inicial. En false, el catalogo arranca vacio (Escenario 3 de la HU)
eventify.seeder.enabled=true

# Personalizacion de Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=none
